Repository IkumaTadokoro/jp_local_gov, pull requests merged in 2022-01, with the labels that each got.

#77 Loosen supported ruby version to 2.7
  .github/workflows/lint.yml
  .github/workflows/steep.yml
  .github/workflows/test.yml
  .rubocop.yml
  .ruby-version
  jp_local_gov.gemspec
  lib/jp_local_gov.rb
  lib/jp_local_gov/random.rb
Labels: enhancement

#81 Fix test ci name
  .github/workflows/test.yml
Labels: bug, misc

#82 Fix Ruby(3.0) to be recognized as float
  .github/workflows/lint.yml
  .github/workflows/steep.yml
  .github/workflows/test.yml
Labels: misc
